const images = {
  logo: "/assets/images/logo2.png",
  img1: "/assets/images/image1.jpg",
  img2: "/assets/images/image2.jpg",
  img3: "/assets/images/image3.jpg",
  img4: "/assets/images/image4.png",
  img5: "/assets/images/image5.png",
  img6: "/assets/images/image6.jpg",
  img7: "/assets/images/image7.jpg",
  img8: "/assets/images/image8.png",
  img9: "/assets/images/image9.jpg",
  img10: "/assets/images/image10.jpg",
  img11: "/assets/images/image11.jpg",
  img12: "/assets/images/image12.jpg",
  img13: "/assets/images/image13.jpg",
  img14: "/assets/images/image14.jpg",
  img15: "/assets/images/image15.jpg",
  img16: "/assets/images/image16.jpg",
  img17: "/assets/images/image17.jpg",
  img18: "/assets/images/image18.jpg",
  img19: "/assets/images/image19.jpg",
  img20: "/assets/images/image20.jpg",
  img21: "/assets/images/image21.png",
  img22: "/assets/images/image22.jpg",
  img23: "/assets/images/image23.jpg",
  img24: "/assets/images/image24.jpg",
  img25: "/assets/images/image25.jpg",
  img26: "/assets/images/image26.jpg",
  img27: "/assets/images/image27.jpg",
  img28: "/assets/images/image28.jpg",
  img29: "/assets/images/image29.jpg",
  img30: "/assets/images/image30.png",
};

export default images;
