export const PATH = {
  HOME: "/",
  ABOUT: "/about",
  NODE1: "/node-1",
  NODE2: "/node-2",
  NODECONTROL: "/node-control",
  SIGNUP: "/signup",
  SIGNIN: "/signin",
  FORGOTPASSWORD: "/forgot-password",
  ERRORPAGE: "/error-page",
  ACCOUNTDETAIL: "/account-detail",
  CHANGEPASSWORD: "/change-password",
  CHANGEINFOMATION: "/change-infomation",
  CONTACT: "/contact",
};
